server:
  port: 8001
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true

spring:
  cloud:
    gateway:
      mvc:
        routes[0]:
          id: cities
          predicates[0]: Path=/customerservice/api/v1/cities/**
          uri: lb://customerservice
        routes[1]:
          id: individualCustomer
          predicates[0]: Path=/customerservice/api/v1/individualCustomers/**
          uri: lb://customerservice
        routes[2]:
          id: addres
          predicates[0]: Path=/customerservice/api/v1/addresses/**
          uri: lb://customerservice
        routes[3]:
          id: contactMedium
          predicates[0]: Path=/customerservice/api/v1/contactMediums/**
          uri: lb://customerservice
        routes[4]:
          id: searchservice
          predicates[0]: Path=/searchservice/api/v1/searchCustomers/**
          uri: lb://searchservice
        routes[5]:
          id: discoveryserver
          predicates[0]: Path=/eureka/web
          filters[0]: SetPath=/
          uri: http://localhost:8888
